version: 2.1

orbs:
  rafay: rafaysystems/rafay@1.0.5


jobs:
  build_publish:
    docker:
      - image: $AWS_BASE_IMAGE_URI
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

    steps:
      - checkout
      - setup_remote_docker

      - run: 
          name: Compile and build bikeshed files 
          command: sh compile.sh

      - run:
          name: Build the DID Alliance Specification Docker image
          command: docker build -t did-spec:latest .

      - run:
          name: Tag the docker image
          command: docker tag did-spec:latest $AWS_REPO_ECR_URI:$CIRCLE_SHA1

      - run:
          name: Push the DID Alliance Specification docker image to ECR
          command: docker push $AWS_REPO_ECR_URI:$CIRCLE_SHA1


  deploy:
      docker:
        - image: $AWS_BASE_IMAGE_URI
          aws_auth:
            aws_access_key_id: $AWS_ACCESS_KEY_ID
            aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

      steps:
        - checkout
        - run:
            name: Checkout Infrastructure Live and Infrastructure Modules repos
            command: git clone -b develop git@bitbucket.org:digitaltrustnetworks/infrastructure-live.git && git clone -b develop git@bitbucket.org:digitaltrustnetworks/infrastructure-modules.git && pwd

        - run:
            name: Export the Infrastructure Modules Path
            command: echo export INFRA_MODULES_DIR='infrastructure-modules/services/dtx-helm-charts'  >> $BASH_ENV

        - run:
            name: Update Appropriate values file
            command: .circleci/updateValuesFile.sh

        - rafay/init

        - rafay/update_workload:
            yaml_file: $INFRA_MODULES_DIR/rafay-workload-spec-template.yaml

        - rafay/publish_workload:
            workload: $RAFAY_WORLOAD_NAME

        - rafay/check_workload_status:
            workload: $RAFAY_WORLOAD_NAME


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_publish:
          filters:
            branches:
              only:
                - master
                - circleci-project-setup
            tags:
              only: /.*/
      - deploy:
          requires:
            - build_publish
          filters:
            tags:
              only: /.*/