#!/usr/bin/env python3
"""
Finish D-404, D-406, D-408, D-411, D-413 — the architecture items whose prose
was corrected but whose examples, duplicates or contradictions were not.

    python3 defects/apply_architecture.py --dry-run
    python3 defects/apply_architecture.py

D-404  Five digital_address values in Appendix B still break the grammar
       stated in clause 7.4.1 (local@interchange). Correct them.
D-406  Two prose sentences still say "pairwise". Replace per TRANSACTION_DIDS §4.
D-408  "Credential Provider" x2 -> "Credential Issuer", the defined term.
D-411  The role-VC contents list appears in 5.5.3 and 6.7.4 and the two differ
       on the assurance bullet. Delete the 5.5.3 copy; cross-reference 6.7.4.
D-413  6.7.4 says role VCs carry "PII (encrypted by issuer)" and "HIDA
       information". Privacy 13.6 forbids publishing enrolment PII and 13.7
       forbids HIDA in any credential. Reconcile 6.7.4 to the privacy clause.

Safe to re-run.
"""

import sys, os, re, json

HERE = os.path.dirname(os.path.abspath(__file__))
SPEC = os.path.join(HERE, "..", "spec", "adia_v3.md")

DA = [
 ('"digital_address": "agd_admin@global_1"',          '"digital_address": "agd_admin@agd"'),
 ('"digital_address": "issuer_admin@issuer_1"',       '"digital_address": "issuer_admin@ix_1"'),
 ('"digital_address": "sp_admin@service_provider_1"', '"digital_address": "sp_admin@ix_1"'),
 ('"digital_address": "USER_DA@IX_1"',                '"digital_address": "user2@ix_1"'),
 ('"digital_address": "issuer1@ix3.r1"',              '"digital_address": "issuer1@ix_3"'),
]

PROSE = [
 # D-406
 ("> Note 3 to entry:  Every ADI-Network entity has a primary DID that includes its own cryptographic keys that can be used for digital signing and data encryption. ADI-Network entities may also have temporary, pairwise DIDs for session use.",
  "> Note 3 to entry: Every ADI-Network entity has one primary DID. The DIDdoc bound to that DID references the keys used for signing and encryption. A User may additionally be represented by transaction DIDs, generated by its Interchange for single presentations; see clause 7.4.4."),
 ("bound to an ADI-Network DID and may be bound to one or more privacy preserving pairwise DIDs",
  "bound to one primary ADI-Network DID, and may additionally be represented by transaction DIDs as specified in clause 7.4.4"),
 # D-408
 ("3.  A Credential Provider is an organization that can collect, validate, package and then issue",
  "3.  A Credential Issuer is an organization that can collect, validate, package and then issue"),
 ("3.  VC Issuer – A Credential Provider connects to the ADI-Network via a VC Issuer role",
  "3.  VC Issuer – A Credential Issuer connects to the ADI-Network via a VC Issuer role"),
 ("Issuer functions can be deployed by the Credential Provider or by the VC Issuer Agent",
  "Issuer functions can be deployed by the Credential Issuer or by the VC Issuer Agent"),
 # D-413, in the surviving 6.7.4 list
 ("- PII (As required per governance policy, encrypted by issuer)",
  "- Legal name and a contact URI for organisational participants (Providers, Credential Issuers, Service Providers); no personal information for Users (clause 13.6)"),
]

# D-411: the 5.5.3 copy, from its introducing sentence through its last bullet
D411_START = "Actors on an ADI-Network have an ADI-ROLE VC that defines:"
D411_END   = "- Digital Address\n"
D411_REPL  = "Actors on an ADI-Network have an ADI-ROLE VC whose contents are specified in clause 6.7.4.\n"


def main():
    dry = "--dry-run" in sys.argv
    text = open(SPEC, encoding="utf-8").read()
    done, skipped = [], []

    for a, b in DA:
        if a in text: text = text.replace(a, b); done.append("D-404 " + b)
        elif b in text: skipped.append("D-404 already: " + b)
        else: skipped.append("D-404 not found: " + a[:40])

    for a, b in PROSE:
        tag = "D-406" if "pairwise" in a else ("D-408" if "Credential Provider" in a else "D-413")
        if a in text: text = text.replace(a, b, 1); done.append("%s %s" % (tag, b[:60]))
        elif b in text: skipped.append("%s already applied" % tag)
        else: skipped.append("%s not found: %s" % (tag, a[:50]))

    # D-411: remove the first (5.5.3) copy of the list
    i = text.find(D411_START)
    if i != -1:
        j = text.find(D411_END, i)
        if j != -1 and j - i < 1500:
            text = text[:i] + D411_REPL + text[j + len(D411_END):]
            done.append("D-411 5.5.3 role-VC list replaced with cross-reference to 6.7.4")
        else:
            skipped.append("D-411 list end not found")
    elif D411_REPL.strip() in text:
        skipped.append("D-411 already applied")

    # D-413: HIDA must not appear in a credential (13.7); remove from the 6.7.4 list
    n = text.count("\n- HIDA information\n")
    if n:
        text = text.replace("\n- HIDA information\n", "\n"); done.append("D-413 'HIDA information' removed from role-VC contents (x%d)" % n)

    for l in done:    print("  updated : %s" % l)
    for l in skipped: print("  skipped : %s" % l)

    for blk in re.findall(r"```json\n(.*?)\n```", text, re.S):
        try: json.loads(blk)
        except Exception as e: print("  ABORTED: JSON no longer parses"); sys.exit(1)

    if dry: print("\n  --dry-run: nothing written"); return
    if not done: print("\n  nothing to change"); return
    open(SPEC, "w", encoding="utf-8").write(text)
    print("\n  written -- now run: make notes")


if __name__ == "__main__":
    main()
