#!/usr/bin/env python3
"""
D-405 / decision D9: specify how a HIDA is constructed.

    python3 defects/apply_hida_construction.py --dry-run
    python3 defects/apply_hida_construction.py

Adds clauses 7.4.2.1 (construction: HMAC-SHA-256 under an Interchange-held HSM
key), 7.4.2.2 (canonicalisation) and 7.4.2.3 (retention) after the existing
"HIDA usage is REQUIRED" paragraph. Safe to re-run.
"""

import sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
SPEC = os.path.join(HERE, "..", "spec", "adia_v3.md")

ANCHOR = ("HIDA usage is REQUIRED. An Interchange cannot satisfy §7.4.1 without it. The choice of contributing PII "
          "attributes is set by governance policies; the requirement to perform the comparison is not optional.")

CLAUSE = '''

**7.4.2.1 Construction.** An Interchange MUST compute a HIDA as

```
HIDA = HMAC-SHA-256( K, canon(a1) || 0x1F || canon(a2) || 0x1F || ... || canon(an) )
```

where `K` is a 256-bit key generated by the Interchange and held in the same hardware security module as its signing keys, `a1 … an` are the contributing attributes in the fixed order stated in governance policy, `0x1F` is the ASCII unit-separator octet, and `canon` is the canonicalisation of 7.4.2.2. The key `K` MUST NOT leave the Interchange, MUST NOT be shared with any other participant, and MUST be rotated only by recomputing every stored HIDA under the new key.

An unkeyed digest is not acceptable: the attribute space is small and structured, and an unkeyed hash of name, date of birth and identity-document number is recoverable by exhaustive search.

**7.4.2.2 Canonicalisation.** Before hashing, each textual attribute MUST be normalised as follows, in order:

1. Unicode normalisation to NFKC.
2. Case folding (Unicode full case folding).
3. Removal of all whitespace and of all punctuation characters (Unicode categories P* and Z*).
4. Transliteration of remaining non-ASCII letters to their closest ASCII equivalents, using a transliteration table fixed by governance policy.

Dates MUST be expressed as `YYYYMMDD`. Identity-document numbers MUST have all non-alphanumeric characters removed before case folding. Personal names MUST be supplied as separate given-name and family-name attributes, never as a single string, so that name order cannot affect the result.

Two enrolments that differ only in case, whitespace, punctuation, diacritics or name order therefore yield the same HIDA. Two enrolments that differ in any contributing attribute's substance yield different HIDAs.

**7.4.2.3 Retention.** A HIDA is personal information (clause 13.7). An Interchange MUST retain a participant's HIDA only while that participant holds a Digital Address issued by it, plus any period required by law, and MUST delete it thereafter.'''


def main():
    dry = "--dry-run" in sys.argv
    text = open(SPEC, encoding="utf-8").read()
    if "7.4.2.1 Construction" in text:
        print("  already applied"); return
    if ANCHOR not in text:
        print("  anchor paragraph not found -- run apply_hida.py first"); sys.exit(1)
    text = text.replace(ANCHOR, ANCHOR + CLAUSE, 1)
    print("  7.4.2.1 Construction, 7.4.2.2 Canonicalisation, 7.4.2.3 Retention added")
    if dry: print("\n  --dry-run: nothing written"); return
    open(SPEC, "w", encoding="utf-8").write(text)
    print("\n  written -- now run: make notes")


if __name__ == "__main__":
    main()
