#!/usr/bin/env python3
"""
Generate the Editor's Notes clause from the live defect register.

    python3 defects/make_editors_notes.py            # write into the spec
    python3 defects/make_editors_notes.py --preview  # print, do not write

The clause is delimited by HTML comment markers, so re-running replaces it in
place. Run it after every editing session and the section stays current.

Sources:
  defects/defects.yaml   descriptions, severities, owners, blocked_by
  adia_checks.py         live pass/fail for the 70-odd automated checks
  spec/adia_v3.md        the document itself
"""

import sys, os, re, subprocess, datetime, collections
import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
SPEC = os.path.join(HERE, "..", "spec", "adia_v3.md")
YAML = os.path.join(HERE, "defects.yaml")

START = "<!-- EDITORS-NOTES-START — generated by make_editors_notes.py, do not edit by hand -->"
END   = "<!-- EDITORS-NOTES-END -->"

# Open architectural decisions. Text is stable; membership is driven by blocked_by.
DECISIONS = {
 "D1":  ("Legacy field prefix",
         "Appendix B field names carry an `ard_` prefix from a role that no longer exists in the architecture. Retain the role, or rename the fields."),
 "D2":  ("DID syntax",
         "Decided 23 September 2026: the identifier is opaque, `did:adi:<id>` with `<id>` the unpadded base64url encoding of at least 128 bits of entropy, carrying no region, Interchange or other structure. Resolution is through the ADI Global Domain's network directory. Clause 7.4.3 states the syntax. Remaining: registration of the `did:adi` method in the W3C DID Specification Registries, and redrawing Figure 10."),
 "D3":  ("Digital Address grammar",
         "The Digital Address form is stated but not given a grammar, and case sensitivity, reserved names and internationalised labels are unaddressed."),
 "D4":  ("Role credential type registry",
         "Five competing naming schemes are used for the same five credential types. A single registry is required, and the entitlement values in the examples corrected to match."),
 "D5":  ("Relationship to OpenID for Verifiable Credential Issuance",
         "The issuance flow borrows the shape of OpenID4VCI without conforming to it. The draft must either profile a named version, with a delta table, or state that it defines an independent protocol."),
 "D6":  ("Credential format",
         "Selective disclosure is described in the narrative but cannot be performed with the credential format the examples use. Adopting SD-JWT VC would provide it, together with holder binding and a status mechanism; retaining the present format means withdrawing the selective disclosure claims."),
 "D7":  ("Signature algorithms",
         "No mandatory-to-implement algorithm set is stated. The examples and the issuer metadata disagree. A set must be named, with a prohibition on algorithm substitution."),
 "D8":  ("Assurance levels",
         "Superseded: identity, authentication and federation assurance are now carried as three separate values, and the maximum assertable levels are stated in clause 7.2.4."),
 "D9":  ("HIDA construction",
         "Decided 23 September 2026: HMAC-SHA-256 under a key held by the enrolling Interchange, over canonicalised attributes (NFKC, case folding, whitespace and punctuation removed, ASCII transliteration). Specified in clause 7.4.2.1 to 7.4.2.3."),
 "D10": ("Credential vault discovery",
         "A credential may be held in the issuer's vault or the user's, but the metadata carries a single endpoint and no mechanism is defined for discovering a user vault."),
 "D11": ("Control of the signing key",
         "Partially resolved by clause 7.2.4. The remaining question is the certification regime required of the hardware security module and the audit obligations on the Interchange."),
 "D13": ("Location of authority: role credentials or DID Documents",
         "Decided 22 September 2026. ADI-ROLE Verifiable Credentials are retained. They are issued by the onboarding "
         "Interchange for Credential Issuers, Service Providers and Users; the ADI Global Domain issues only the "
         "Interchange's own credential and approves and lists Issuers in the network directory. This is the design "
         "the draft already describes. An alternative carrying authority in the DID Document was considered and not "
         "adopted. A verifier's check of the Issuer's entitlement for the credential type is mandatory; see clause 6.6 "
         "and the verification procedure."),
 "D12": ("Transaction identifiers",
         "Resolved in principle: single-use identifiers generated by the Interchange on the user's behalf. The mechanism depends on D6, because an identifier applied to the presentation does not prevent correlation while the credential it carries names the subject."),
}

# workstream -> (clause grouping, heading)
GROUPS = [
 ("normative",          "Normative structure and conformance"),
 ("crypto-protocol",    "Cryptography and protocol"),
 ("data-model",         "Data model and schemas"),
 ("architecture",       "Architecture and terminology"),
 ("references-tooling", "References, figures and tooling"),
 ("editorial",          "Editorial"),
]

SEV = {"S1": "Critical", "S2": "Major", "S3": "Minor"}


def live_status():
    out = subprocess.run([sys.executable, os.path.join(HERE, "adia_checks.py"), SPEC, "--status"],
                         capture_output=True, text=True).stdout
    return dict(l.split(",") for l in out.strip().split("\n") if "," in l)


def resolve(e, res):
    s = e.get("status", "Open")
    if e.get("check") == "auto":
        live = res.get(e["id"], "Open")
        if live == "Verified":
            return "Verified"
        return "Blocked(%s)" % e["blocked_by"] if e.get("blocked_by") else "Open"
    if e.get("blocked_by") and s == "Open":
        return "Blocked(%s)" % e["blocked_by"]
    return s


def clean(t):
    """one-line, no internal newlines, trimmed"""
    return re.sub(r"\s+", " ", str(t or "")).strip()


def clause_number():
    """One more than the highest numbered top-level clause before the notes / appendices."""
    t = open(SPEC, encoding="utf-8").read()
    cut = t.find("<!-- EDITORS-NOTES-START")
    if cut == -1:
        cut = t.find("# Appendix A")
    nums = [int(x) for x in re.findall(r"^# (\d+)\.", t[:cut] if cut != -1 else t, re.M)]
    return (max(nums) + 1) if nums else 12


def build():
    N = clause_number()
    d = yaml.safe_load(open(YAML, encoding="utf-8"))
    res = live_status()

    rows = []
    for e in d["defects"]:
        st = resolve(e, res)
        if st in ("Verified", "Rejected") or st.startswith("Superseded"):
            continue
        rows.append({
            "id": e["id"], "sev": e["severity"], "status": st,
            "ws": e["workstream"], "loc": clean(e.get("location")),
            "what": clean(e.get("defect")), "need": clean(e.get("fix")),
            "blocked": e["blocked_by"] if (st.startswith("Blocked") and e.get("blocked_by")) else None,
        })

    n_total = len(rows)
    n_crit = sum(1 for r in rows if r["sev"] == "S1")
    n_blocked = sum(1 for r in rows if r["blocked"])
    n_fixed = sum(1 for r in rows if r["status"] == "Fixed")
    decisions_used = sorted({r["blocked"] for r in rows if r["blocked"]},
                            key=lambda x: int(x[1:]))

    L = [START, ""]
    L.append('<a id="editors-notes"></a>')
    L.append("# %d. Editor's Notes — work still needed" % N)
    L.append("")
    L.append("*This clause is generated from the editing register maintained alongside this draft. "
             "It was last regenerated on %s and reflects the state of the text at that point.*"
             % datetime.date.today().strftime("%d %B %Y"))
    L.append("")
    L.append("This clause records work the editors know to be outstanding. It is provided so that a "
             "Study Group taking this draft forward can see what has been identified but not yet "
             "resolved, rather than having to rediscover it. Items are numbered for reference; the "
             "numbering is that of the editing register and is not sequential within this clause.")
    L.append("")
    L.append("| | |")
    L.append("|---|---|")
    L.append("| Items outstanding | %d |" % n_total)
    L.append("| Of which critical | %d |" % n_crit)
    L.append("| Awaiting an architectural decision | %d |" % n_blocked)
    L.append("| Open decisions | %d |" % len(decisions_used))
    L.append("| Corrected, awaiting confirmation | %d |" % n_fixed)
    L.append("")
    L.append("Severity is recorded as **Critical** where the text as written would lead an "
             "implementer to build something incorrect or insecure, **Major** where the text is "
             "contradictory or where required normative material is absent, and **Minor** where the "
             "issue is editorial.")
    L.append("")

    # ---- 12.1 decisions ----
    L.append('<a id="editors-notes-decisions"></a>')
    L.append("## %d.1 Architectural decisions required" % N)
    L.append("")
    L.append("The following questions are unresolved. Each blocks one or more of the items in clause "
             "%d.2, and they are listed first because the drafting that follows depends on them." % N)
    L.append("")
    for k in decisions_used:
        title, body = DECISIONS.get(k, ("Decision %s" % k, "Description not recorded."))
        dep = sorted(r["id"] for r in rows if r["blocked"] == k)
        L.append("**%s — %s**" % (k, title))
        L.append("")
        L.append(body)
        L.append("")
        L.append("*Blocks: %s*" % ", ".join(dep))
        L.append("")

    # ---- 12.2 items by grouping ----
    L.append('<a id="editors-notes-items"></a>')
    L.append("## %d.2 Outstanding items" % N)
    L.append("")
    sub = 0
    for ws, heading in GROUPS:
        group = [r for r in rows if r["ws"] == ws]
        if not group:
            continue
        sub += 1
        order = {"S1": 0, "S2": 1, "S3": 2}
        group.sort(key=lambda r: (order.get(r["sev"], 3), r["id"]))
        L.append('<a id="editors-notes-%s"></a>' % ws)
        L.append("### %d.2.%d %s" % (N, sub, heading))
        L.append("")
        L.append("| Ref | Severity | Clause or object | Issue | Work needed |")
        L.append("|---|---|---|---|---|")
        for r in group:
            note = r["need"]
            if r["blocked"]:
                note = "%s *(awaiting %s)*" % (note, r["blocked"]) if note else "Awaiting %s." % r["blocked"]
            L.append("| %s | %s | %s | %s | %s |" % (
                r["id"], SEV.get(r["sev"], r["sev"]), r["loc"] or "—",
                r["what"] or "—", note or "—"))
        L.append("")

    # ---- 12.3 major absent material ----
    absent = [r for r in rows if r["id"] in
              ("C-303", "C-304", "C-305", "C-306", "C-307", "C-308", "B-209", "B-210", "A-127")]
    if absent:
        L.append('<a id="editors-notes-absent"></a>')
        L.append("## %d.3 Normative material not yet drafted" % N)
        L.append("")
        L.append("The items below are not corrections to existing text but clauses that do not yet "
                 "exist. They are listed separately because they represent the larger part of the "
                 "drafting effort remaining.")
        L.append("")
        for r in sorted(absent, key=lambda r: r["id"]):
            L.append("- **%s** — %s" % (r["id"], r["what"]))
        L.append("")

    L.append("*End of Editor's Notes.*")
    L.append("")
    L.append(END)
    return "\n".join(L), n_total


def main():
    body, n = build()
    if "--preview" in sys.argv:
        print(body); return

    text = open(SPEC, encoding="utf-8").read()
    if START in text and END in text:
        a = text.index(START); b = text.index(END) + len(END)
        text = text[:a] + body + text[b:]
        action = "replaced"
    else:
        m = re.search(r"^<a id=\"[^\"]*\"></a>\n# Appendix A", text, re.M) or \
            re.search(r"^# Appendix A", text, re.M)
        if not m:
            print("  could not find Appendix A; clause not inserted"); sys.exit(1)
        text = text[:m.start()] + body + "\n\n" + text[m.start():]
        action = "inserted"
    open(SPEC, "w", encoding="utf-8").write(text)
    print("  Editor's Notes %s — %d items outstanding" % (action, n))


if __name__ == "__main__":
    main()
