#!/usr/bin/env python3
"""
Render the defect register.

    python3 render.py                 # write defects/register.md
    python3 render.py --check         # exit 1 if register.md is stale

Ownership, so nothing is ever edited in two places:

    defects.yaml     hand-edited   owner, notes, fix, and status for
                                   defects with no automated check
    adia_checks.py   hand-edited   the checks themselves
    register.md      GENERATED     never hand-edit; regenerate instead

For any defect carrying `check: auto`, the harness result overwrites whatever
status the YAML holds. That is deliberate: those statuses are a property of the
spec file, not an opinion about it.
"""

import sys, os, subprocess, datetime
import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
YAML = os.path.join(HERE, "defects.yaml")
OUT  = os.path.join(HERE, "register.md")

WS_TITLE = {
    "data-model":        "A — Data model and examples",
    "crypto-protocol":   "B — Cryptography and protocol",
    "normative":         "C — Normative structure and conformance",
    "architecture":      "D — Architecture and terminology",
    "editorial":         "E — Editorial",
    "references-tooling":"F — References, diagrams and tooling",
}
WS_ORDER = list(WS_TITLE)


def git_ref(defect_id):
    """Newest commit whose message mentions this defect ID."""
    try:
        out = subprocess.run(
            ["git", "log", "--format=%h", "-1", "--grep", defect_id],
            cwd=HERE, capture_output=True, text=True, timeout=10)
        return out.stdout.strip() or ""
    except Exception:
        return ""


def check_results(spec_path):
    """ID -> Verified|Open from the harness. Empty dict if it cannot run."""
    script = os.path.join(HERE, "adia_checks.py")
    if not (os.path.exists(script) and os.path.exists(spec_path)):
        return {}
    try:
        out = subprocess.run([sys.executable, script, spec_path, "--status"],
                             capture_output=True, text=True, timeout=120)
        res = {}
        for line in out.stdout.strip().split("\n"):
            if "," in line:
                k, v = line.split(",", 1)
                res[k.strip()] = v.strip()
        return res
    except Exception:
        return {}


def render():
    doc  = yaml.safe_load(open(YAML, encoding="utf-8"))
    meta = doc.get("meta", {})
    spec = os.path.join(HERE, "..", meta.get("spec", "spec/adia_v3.md"))
    spec = os.path.normpath(spec)
    res  = check_results(spec)

    defects = doc["defects"]
    for d in defects:
        if d.get("check") == "auto" and d["id"] in res:
            live = res[d["id"]]
            # a blocked defect that now passes is genuinely done
            if live == "Verified":
                d["status"] = "Verified"
            elif d["status"] == "Verified":
                d["status"] = "Open"        # regression
        d["_ref"] = git_ref(d["id"])

    n_auto = len([d for d in defects if d.get("check") == "auto"])
    n_ver  = len([d for d in defects if d["status"] == "Verified"])
    n_fix  = len([d for d in defects if d["status"] == "Fixed"])
    n_blk  = len([d for d in defects if d["status"].startswith("Blocked")])
    n_open = len([d for d in defects if d["status"] == "Open"])
    inv    = {k: v for k, v in res.items() if k.startswith("INV-")}
    inv_ok = len([v for v in inv.values() if v == "Verified"])

    L = []
    L.append("# ADIA v3.0 — Defect Register")
    L.append("")
    L.append("<!-- GENERATED by render.py. Do not edit. "
             "Change defects.yaml or the spec, then re-run. -->")
    L.append("")
    L.append("| | |")
    L.append("|---|---|")
    L.append("| Spec under test | `%s` |" % meta.get("spec", "?"))
    L.append("| Rendered | %s |" % datetime.date.today().isoformat())
    L.append("| Defects | %d (%d with an automated check) |" % (len(defects), n_auto))
    L.append("| Verified | %d |" % n_ver)
    L.append("| Fixed, awaiting verification | %d |" % n_fix)
    L.append("| Blocked on a decision | %d |" % n_blk)
    L.append("| Open | %d |" % n_open)
    L.append("| Standing invariants | %d of %d holding |" % (inv_ok, len(inv)))
    L.append("")
    L.append("**Status values.** `Open` · `Fixed` (author's claim) · `Verified` "
             "(harness passes, or a second reviewer confirmed) · `Blocked(Dn)` · "
             "`Rejected` · `Superseded(ID)`.")
    L.append("")
    L.append("Nobody moves their own work to `Verified`. For the %d automated "
             "defects the harness does it; for the other %d a second person does."
             % (n_auto, len(defects) - n_auto))
    L.append("")
    L.append("---")
    L.append("")

    for ws in WS_ORDER:
        rows = [d for d in defects if d["workstream"] == ws]
        if not rows:
            continue
        done = len([d for d in rows if d["status"] == "Verified"])
        L.append("## Workstream %s" % WS_TITLE[ws])
        L.append("")
        L.append("%d defects · %d verified · %d with an automated check"
                 % (len(rows), done, len([d for d in rows if d.get("check") == "auto"])))
        L.append("")
        L.append("| ID | Sev | Status | Owner | Check | Location | Defect | Fix | Ref |")
        L.append("|---|---|---|---|---|---|---|---|---|")
        for d in rows:
            L.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
                d["id"], d["severity"], d["status"],
                d.get("owner") or "", "`auto`" if d.get("check") == "auto" else "—",
                d.get("location", ""), d.get("defect", ""), d.get("fix", ""),
                ("`%s`" % d["_ref"]) if d["_ref"] else ""))
        L.append("")

    if inv:
        L.append("---")
        L.append("")
        L.append("## Standing invariants")
        L.append("")
        L.append("Properties that must never regress. Not defects — guardrails.")
        L.append("")
        L.append("| Check | Holding |")
        L.append("|---|---|")
        for k in sorted(inv):
            L.append("| `%s` | %s |" % (k, "yes" if inv[k] == "Verified" else "**NO**"))
        L.append("")

    open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
    return n_ver, len(defects)


def main():
    if "--check" in sys.argv:
        before = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        render()
        after = open(OUT, encoding="utf-8").read()
        if before != after:
            print("register.md is stale — run `make register` and commit the result")
            sys.exit(1)
        print("register.md is current")
        return
    v, n = render()
    print("wrote %s  (%d of %d verified)" % (OUT, v, n))


if __name__ == "__main__":
    main()
