name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Install bikeshed
        run: sudo python3 --version && sudo apt-get update -y && sudo apt-get -y install python3-pip && sudo pip3 install bikeshed && sudo bikeshed update

      - uses: actions/checkout@v2

      - name: Output to HTML
        run: ./compile.sh

      - name: Publish HTML to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
